spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupon?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234  # 修改这里
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 自动建表
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
server:
  port: 8081

